// Editorial evidence is independent of the automatic WDI snapshot. Never renew a review date on fetch.
export const DOSSIER_VERSION = "2.0.0";
export const DOSSIER_REVIEW_DATE = "2026-09-03";
export type EvidenceLayer = "entry" | "education" | "cost";
export type EvidenceKind = "requirement" | "directory" | "estimate" | "guidance";
export type Currency = "EUR" | "GBP" | "CAD" | "USD" | "JPY";
export type RegisteredSource = {
  id: string; country: string; title: string; publisher: string; url: string;
  kind: "government" | "public-agency" | "university" | "university-association";
  reviewedAt: string | null; status: "reviewed" | "limited" | "unconfirmed";
  note: string; markers: string[]; automaticCheck: boolean;
};
export type DossierClaim = {
  id: string; country: string; layer: EvidenceLayer; kind: EvidenceKind; title: string;
  summary: string; sourceId: string; audience: string; limits: string;
  referencePeriod: string; reviewedAt: string; reviewDays: number;
  effectiveFrom?: string; effectiveUntil?: string; questions: string[];
};
export type CostReference = {
  id: string; country: string; sourceId: string; title: string; location: string;
  currency: Currency; low: number; high: number; periodMonths: number;
  category: "living" | "total-study"; referencePeriod: string;
  audience: string; includes: string; excludes: string; historical: boolean;
};
const source = (s: Omit<RegisteredSource, "reviewedAt" | "status" | "automaticCheck"> & Partial<Pick<RegisteredSource, "reviewedAt" | "status" | "automaticCheck">>): RegisteredSource => ({ reviewedAt: DOSSIER_REVIEW_DATE, status: "reviewed", automaticCheck: true, ...s });
export const DOSSIER_SOURCES: RegisteredSource[] = [
  source({ id: "pt-dges", country: "portugal", title: "Courses and institutions", publisher: "DGES — Portugal", kind: "government", url: "https://www.dges.gov.pt/simges/public/www/cursos_instituicoes", markers: ["Cursos", "Instituições"], note: "Official course and institution search. Listing does not establish admission, fees or professional recognition." }),
  source({ id: "pt-fees", country: "portugal", title: "University of Lisbon tuition policy", publisher: "Universidade de Lisboa", kind: "university", url: "https://www.ulisboa.pt/en/info/tuition-fees", markers: ["2026/2027", "international students"], note: "2026/27 policy distinguishes regulated fees from international-student and programme-specific fees." }),
  source({ id: "pt-aima", country: "portugal", title: "Higher-education residence route", publisher: "AIMA — Portugal", kind: "government", url: "https://aima.gov.pt/pt/estudar/autorizacao-de-residencia-emitida-a-estudantes-do-ensino-superior-art-o-91", markers: [], reviewedAt: null, status: "unconfirmed", automaticCheck: false, note: "Primary authority identified, but the research tool could not retrieve this page. No legal rule is certified from this link. Confirm directly with AIMA and the responsible consulate." }),
  source({ id: "de-visa", country: "germany", title: "Visa for studying", publisher: "German Federal Government — Make it in Germany", kind: "government", url: "https://www.make-it-in-germany.com/en/visa-residence/types/studying", markers: ["11,904", "2026"], note: "Study and study-place-seeking routes are different. Amounts and permissions must not be transferred between them." }),
  source({ id: "de-directory", country: "germany", title: "Higher education institutions", publisher: "German Rectors’ Conference — Hochschulkompass", kind: "university-association", url: "https://www.hochschulkompass.de/en/higher-education-institutions.html", markers: ["higher education"], note: "Institution and programme research; not an individual admission or credential-recognition decision." }),
  source({ id: "de-cost", country: "germany", title: "Costs of education and living", publisher: "DAAD", kind: "university-association", url: "https://www.daad.de/en/studying-in-germany/living-in-germany/finances/", markers: ["900", "1,200"], note: "Planning guidance without an explicit reference year for the monthly range. Not a city-price series." }),
  source({ id: "uk-funds", country: "united-kingdom", title: "Student visa: money you need", publisher: "UK Government", kind: "government", url: "https://www.gov.uk/student-visa/money", markers: ["1,529", "1,171", "28 days"], note: "Financial-evidence rules include exemptions, dependants and timing. Check the full official guidance." }),
  source({ id: "uk-degree", country: "united-kingdom", title: "Check degree-awarding recognition", publisher: "UK Government", kind: "government", url: "https://www.gov.uk/check-university-award-degree", markers: ["award a degree", "recognised"], note: "The teaching institution and awarding institution can differ. The checks vary across the UK nations." }),
  source({ id: "uk-oxford", country: "united-kingdom", title: "Oxford living costs, 2026–27", publisher: "University of Oxford", kind: "university", url: "https://www.ox.ac.uk/students/fees-funding/living-costs", markers: ["1,405", "2,105", "2026-27"], note: "Single full-time undergraduate or graduate student without dependants, living in Oxford. No affiliation with TGPI." }),
  source({ id: "ca-funds", country: "canada", title: "Study permit: financial support", publisher: "Immigration, Refugees and Citizenship Canada", kind: "government", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/get-documents/financial-support.html", markers: ["23,448", "September 1, 2026", "Quebec"], note: "Updated 2026-08-28. New table applies to applications from 2026-09-01, outside Quebec. It is not a living-cost estimate." }),
  source({ id: "ca-dli", country: "canada", title: "Designated learning institutions", publisher: "Immigration, Refugees and Citizenship Canada", kind: "government", url: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada/study-permit/prepare/designated-learning-institutions-list.html", markers: ["Designated learning institutions", "Not all programs"], note: "DLI designation, programme-level PGWP eligibility and individual eligibility are different checks." }),
  source({ id: "us-visa", country: "united-states", title: "Student visa", publisher: "U.S. Department of State", kind: "government", url: "https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html", markers: ["Student Visa", "Form I-20"], note: "F and M study categories depend on the intended course. A visa does not guarantee admission at the border." }),
  source({ id: "us-mit", country: "united-states", title: "MIT graduate cost of attendance, 2026–27", publisher: "MIT Student Financial Services", kind: "university", url: "https://sfs.mit.edu/graduate-students/cost-of-attendance/grad-cost-of-attendance/", markers: ["109,017", "2026", "9-month"], note: "Institution-specific published budget before aid; some programmes have non-standard tuition. No affiliation with TGPI." }),
  source({ id: "jp-visa", country: "japan", title: "General visa: Student", publisher: "Japan Ministry of Foreign Affairs", kind: "government", url: "https://www.mofa.go.jp/j_info/visit/visa/long/visa6.html", markers: ["Certificate of Eligibility", "does not guarantee"], note: "The page is dated 2023-03-17. Confirm current mission-specific requirements; a COE does not guarantee a visa." }),
  source({ id: "jp-schools", country: "japan", title: "Search for schools", publisher: "JASSO — Study in Japan", kind: "public-agency", url: "https://www.studyinjapan.go.jp/en/search-for-schools/school_search.php?lang=en", markers: ["Search for schools", "does not include all"], note: "School-supplied information, with incomplete coverage. Confirm the latest programme details directly with the school." }),
  source({ id: "jp-cost", country: "japan", title: "International-student living expenses", publisher: "JASSO — Study in Japan", kind: "public-agency", url: "https://www.studyinjapan.go.jp/en/life/cost-of-living/", markers: ["105,000", "2023"], note: "The student living-cost average is from the 2023 survey, even though the same page includes newer retail-price data." }),
  source({ id: "es-entry", country: "spain", title: "Student in Spain", publisher: "European Commission — EU Immigration Portal", kind: "government", url: "https://home-affairs.ec.europa.eu/policies/migration-and-asylum/eu-immigration-portal/student-spain_en", markers: ["Student in Spain", "higher education institution"], status: "limited", note: "General third-country study orientation. No current deadlines, work rights, thresholds or permit durations are extracted; verify with the Spanish authority." }),
  source({ id: "es-qedu", country: "spain", title: "QEDU — university and degree search", publisher: "Spain — university information system", kind: "government", url: "https://siiu.universidades.gob.es/QEDU/", markers: [], reviewedAt: null, status: "unconfirmed", automaticCheck: false, note: "Government directory identified; interactive content could not be retrieved in this review. Verify the exact degree and institution directly." }),
  source({ id: "fr-entry", country: "france", title: "Student route and visa wizard", publisher: "France-Visas — French Government", kind: "government", url: "https://france-visas.gouv.fr/en/etudiant", markers: ["Student", "certificate of enrolment"], status: "limited", note: "Used for route-selection and enrolment evidence only. Other page sections are not imported as current health, work or residence rules." }),
];
const claim = (c: Omit<DossierClaim, "reviewedAt" | "reviewDays"> & Partial<Pick<DossierClaim, "reviewDays">>): DossierClaim => ({ reviewedAt: DOSSIER_REVIEW_DATE, reviewDays: c.kind === "requirement" ? 30 : 90, ...c });
export const DOSSIER_CLAIMS: DossierClaim[] = [
  claim({ id: "pt-programme", country: "portugal", layer: "education", kind: "directory", sourceId: "pt-dges", title: "Verify the institution and the exact course", summary: "DGES provides an official search for higher-education institutions and courses.", audience: "Applicants researching higher education in Portugal.", limits: "A search result is not admission, scholarship eligibility or professional recognition.", referencePeriod: "Directory consulted September 2026", questions: ["Does the institution and exact course appear in DGES?", "Which admission route and language requirements apply to you?"] }),
  claim({ id: "pt-fee-category", country: "portugal", layer: "cost", kind: "guidance", sourceId: "pt-fees", title: "Your fee category changes the budget", summary: "ULisboa distinguishes its regulated 2026/27 fee from international-student fees; master’s and doctoral fees vary by school.", audience: "Prospective ULisboa students, especially international applicants.", limits: "Do not apply the regulated bachelor’s fee to an international applicant without confirmation. No Lisbon housing estimate is published here.", referencePeriod: "Academic year 2026/27", effectiveUntil: "2027-08-31", questions: ["What is your confirmed fee category?", "What does your chosen programme quote for the full academic year?"] }),
  claim({ id: "de-study-route", country: "germany", layer: "entry", kind: "requirement", sourceId: "de-visa", title: "Admission and financial evidence are separate gates", summary: "The federal study-route guidance requires admission to a state-recognised institution and evidence of funding. It cites EUR 11,904 for a blocked account in 2026, with alternative funding evidence possible.", audience: "Applicants using the German higher-education study route; visa exemptions and personal circumstances still matter.", limits: "This is not a city budget, not the study-place-seeking route, and not an eligibility decision. Work rights and family cases require separate confirmation.", referencePeriod: "2026 federal guidance", effectiveUntil: "2026-12-31", questions: ["Is this the admitted-student route or the study-place-seeking route?", "Which funding evidence will your responsible mission accept?"] }),
  claim({ id: "de-institution", country: "germany", layer: "education", kind: "directory", sourceId: "de-directory", title: "Research institutions before comparing programmes", summary: "The German Rectors’ Conference maintains Hochschulkompass for higher-education research.", audience: "Prospective students comparing German institutions.", limits: "Confirm programme language, application conditions and recognition directly; a directory is not an admission guarantee.", referencePeriod: "Directory consulted September 2026", questions: ["Is your exact programme listed?", "Is your prior qualification sufficient for that programme?"] }),
  claim({ id: "de-living", country: "germany", layer: "cost", kind: "estimate", sourceId: "de-cost", title: "Use a student range, then obtain local quotes", summary: "DAAD gives a broad monthly student living-cost range of EUR 900–1,200, varying by location.", audience: "Students planning living expenses in Germany.", limits: "The range has no explicit reference year. It is not a current rent quote or a complete tuition budget.", referencePeriod: "Undated guidance, consulted September 2026", questions: ["What is the actual rent at your destination?", "Which tuition and semester charges sit outside your living budget?"] }),
  claim({ id: "uk-funding", country: "united-kingdom", layer: "entry", kind: "requirement", sourceId: "uk-funds", title: "Visa evidence is not your spending forecast", summary: "The Student visa page lists GBP 1,529 monthly for London or GBP 1,171 outside London, capped at nine months for the living-funds calculation, separately from course fees.", audience: "Student-route applicants subject to the financial-evidence requirement.", limits: "Exemptions, dependants, boarding cases and funding documentation can change the assessment. Where the bank-holding rule applies, inspect the 28-day and application timing conditions. No personal eligibility is calculated.", referencePeriod: "Rules displayed on 2026-09-03", questions: ["Which location and financial-evidence rules apply to your application?", "Are your tuition, dependants and evidence dates covered?"] }),
  claim({ id: "uk-awarding-body", country: "united-kingdom", layer: "education", kind: "directory", sourceId: "uk-degree", title: "Check who actually awards the degree", summary: "The UK government provides recognition checks; the institution teaching a course may differ from the degree-awarding body.", audience: "Applicants to UK degree programmes.", limits: "The appropriate register depends on the UK nation. Recognition does not establish educational quality or admission.", referencePeriod: "Guidance consulted September 2026", questions: ["Who is the degree-awarding institution?", "Have you used the appropriate national recognition check?"] }),
  claim({ id: "uk-oxford-living", country: "united-kingdom", layer: "cost", kind: "estimate", sourceId: "uk-oxford", title: "Oxford: an explicitly scoped student estimate", summary: "Oxford estimates monthly living expenses of GBP 1,405–2,105 for 2026/27.", audience: "Single full-time undergraduate or graduate student without dependants, living in Oxford.", limits: "Not a UK average. Tuition, visa, immigration health surcharge and travel to Oxford need separate planning.", referencePeriod: "Academic year 2026/27", effectiveUntil: "2027-08-31", questions: ["Does the single-student scenario describe you?", "Have you added tuition and arrival expenses separately?"] }),
  claim({ id: "ca-funding-2026", country: "canada", layer: "entry", kind: "requirement", sourceId: "ca-funds", title: "Canada: check the application-date table", summary: "For applications from 1 September 2026, IRCC lists CAD 23,448 in annual living-expense funds for one person outside Quebec, in addition to tuition and transportation.", audience: "Single study-permit applicant, no accompanying family, outside Quebec, applying on or after 2026-09-01.", limits: "A proof-of-funds threshold, not a city living-cost estimate. Family size, Quebec, application date and acceptable evidence require separate checks. Do not assume future earnings will satisfy this requirement.", referencePeriod: "IRCC page updated 2026-08-28", effectiveFrom: "2026-09-01", questions: ["Are you applying under the current table and outside Quebec?", "Have you included tuition, transport and every accompanying family member?"] }),
  claim({ id: "ca-dli-programme", country: "canada", layer: "education", kind: "directory", sourceId: "ca-dli", title: "DLI status is not a work-permit promise", summary: "IRCC lists designated institutions and programme-related distinctions. Not every programme at a DLI qualifies for a post-graduation work permit.", audience: "Applicants choosing a Canadian post-secondary institution and programme.", limits: "Verify the exact campus, programme and individual PGWP conditions. Do not infer work rights from the institution name alone.", referencePeriod: "Directory consulted September 2026", reviewDays: 30, questions: ["Have you recorded the exact campus and DLI number?", "Does the programme meet the current PGWP rules, and do you meet the individual requirements?"] }),
  claim({ id: "us-study-route", country: "united-states", layer: "entry", kind: "requirement", sourceId: "us-visa", title: "Start with the school and the correct visa category", summary: "The Department of State explains student categories and the school-issued Form I-20 used in the F/M application process.", audience: "Applicants researching F or M study in the United States.", limits: "School acceptance, SEVP certification, academic accreditation, visa issuance and admission at the border are distinct. No visa or admission outcome is predicted.", referencePeriod: "Guidance consulted September 2026", questions: ["Does the intended programme use the F or M route?", "Have you confirmed the school’s authority to issue your I-20 and the programme’s academic accreditation?"] }),
  claim({ id: "us-mit-budget", country: "united-states", layer: "cost", kind: "estimate", sourceId: "us-mit", title: "A full institutional budget is not a city average", summary: "MIT publishes a 2026/27 standard graduate cost of attendance of USD 109,017 for nine months, before funding or aid.", audience: "Standard full-time MIT graduate budget for September–May in Cambridge / Greater Boston.", limits: "Includes tuition and other categories; do not compare it directly with living-only estimates. Non-standard programmes, summer registration, dependants and insurance arrangements can change the amount.", referencePeriod: "Academic year 2026/27; nine months", effectiveUntil: "2027-08-31", questions: ["Does your programme use standard tuition?", "What funding is confirmed, and does your actual study period include summer?"] }),
  claim({ id: "jp-coe", country: "japan", layer: "entry", kind: "guidance", sourceId: "jp-visa", title: "A Certificate of Eligibility is not a visa guarantee", summary: "MOFA’s student guidance explains the Certificate of Eligibility and states that it does not guarantee visa issuance.", audience: "Applicants researching Japan’s Student visa route.", limits: "The official page is dated March 2023. Reconfirm current documents and mission-specific requirements before applying; this is not a complete legal checklist.", referencePeriod: "MOFA page dated 2023-03-17", reviewDays: 30, questions: ["Who will coordinate your COE with the school?", "What does the Japanese mission responsible for your residence currently request?"] }),
  claim({ id: "jp-school-search", country: "japan", layer: "education", kind: "directory", sourceId: "jp-schools", title: "Search schools, then confirm directly", summary: "JASSO’s search covers universities, graduate schools and junior colleges accepting international students, using information provided by schools.", audience: "Prospective international students in Japan.", limits: "The directory explicitly says it is not exhaustive. Course language, admission and tuition need direct confirmation.", referencePeriod: "Directory consulted September 2026", questions: ["What is the programme’s language of instruction?", "Has the school confirmed the latest application requirements and fees?"] }),
  claim({ id: "jp-living-2023", country: "japan", layer: "cost", kind: "estimate", sourceId: "jp-cost", title: "Japan: keep the survey year attached", summary: "JASSO reports JPY 105,000 monthly living expenditure from its 2023 privately-financed international-student survey, excluding study and research costs.", audience: "Historical national average for privately-financed international students.", limits: "Not a 2026 price quote, not a Tokyo budget, and not inclusive of tuition. The page’s newer retail statistics do not update this survey result.", referencePeriod: "2023 survey", questions: ["What has changed in rent and prices since 2023?", "Have you collected quotes for your actual city and included tuition?"] }),
  claim({ id: "es-study-orientation", country: "spain", layer: "entry", kind: "guidance", sourceId: "es-entry", title: "Match the institution, study purpose and legal route", summary: "The EU Immigration Portal’s Spain study overview connects recognised study, admission and the relevant permission process.", audience: "Non-EU citizens beginning research on study in Spain.", limits: "Orientation only. The Spanish consular page was access-blocked during this review; current deadlines, funds, work rights and permit duration are not certified here.", referencePeriod: "General overview consulted September 2026", reviewDays: 30, questions: ["Which Spanish consulate or authority handles your place of residence?", "Has it confirmed the current requirements for your course and duration?"] }),
  claim({ id: "fr-study-orientation", country: "france", layer: "entry", kind: "guidance", sourceId: "fr-entry", title: "Use the official wizard for your particular study route", summary: "France-Visas directs students to its visa wizard and identifies enrolment evidence as part of the study application.", audience: "Applicants researching a study stay in France.", limits: "Nationality, residence, course and length of stay matter. This summary does not import the page’s health rules or certify work rights, fees or permit duration.", referencePeriod: "Selected guidance consulted September 2026", reviewDays: 30, questions: ["What route does the official wizard identify for your situation?", "Which enrolment and application steps has your host institution confirmed?"] }),
];
export const COST_REFERENCES: CostReference[] = [
  { id: "oxford-2026", country: "united-kingdom", sourceId: "uk-oxford", title: "Oxford student living costs", location: "Oxford", currency: "GBP", low: 1405, high: 2105, periodMonths: 1, category: "living", referencePeriod: "2026/27", audience: "Single full-time student; no dependants", includes: "Housing, food and listed personal/study expenses", excludes: "Tuition, visa, health surcharge, arrival travel and fieldwork", historical: false },
  { id: "germany-daad", country: "germany", sourceId: "de-cost", title: "DAAD student planning range", location: "Germany — location-dependent", currency: "EUR", low: 900, high: 1200, periodMonths: 1, category: "living", referencePeriod: "Undated guidance; consulted 2026-09-03", audience: "Students; not a specific city or household", includes: "Broad student living categories in DAAD guidance", excludes: "A complete tuition budget and verified local housing quotes", historical: false },
  { id: "japan-jasso-2023", country: "japan", sourceId: "jp-cost", title: "JASSO student survey", location: "Japan — national average", currency: "JPY", low: 105000, high: 105000, periodMonths: 1, category: "living", referencePeriod: "2023 survey — historical", audience: "Privately-financed international students", includes: "Surveyed living expenditure", excludes: "Study and research costs; current local price verification", historical: true },
  { id: "mit-2026", country: "united-states", sourceId: "us-mit", title: "MIT standard graduate budget", location: "Cambridge / Greater Boston", currency: "USD", low: 109017, high: 109017, periodMonths: 9, category: "total-study", referencePeriod: "2026/27; September–May", audience: "Standard full-time graduate programme, before aid", includes: "Published tuition, fees, insurance and living categories", excludes: "Summer; non-standard programme differences; personalised family costs", historical: false },
];
export const DOSSIER_COUNTRIES = ["portugal", "spain", "france", "germany", "united-kingdom", "canada", "united-states", "japan"];
export const COUNTRY_CURRENCIES: Record<string, Currency> = { portugal: "EUR", spain: "EUR", france: "EUR", germany: "EUR", "united-kingdom": "GBP", canada: "CAD", "united-states": "USD", japan: "JPY" };
export function dossierFor(country: string) { return { claims: DOSSIER_CLAIMS.filter(c => c.country === country), sources: DOSSIER_SOURCES.filter(s => s.country === country), costs: COST_REFERENCES.filter(c => c.country === country) }; }
export function sourceFor(id: string) { return DOSSIER_SOURCES.find(s => s.id === id); }
export function referenceReviewState(reference: CostReference, now = new Date()) { const claim = DOSSIER_CLAIMS.find(c => c.sourceId === reference.sourceId && c.layer === "cost"); return claim ? reviewState(claim, now) : "review-due"; }
export function reviewState(c: DossierClaim, now = new Date()): "reviewed" | "review-due" | "not-effective" | "expired" {
  const day = now.toISOString().slice(0, 10);
  if (c.effectiveFrom && day < c.effectiveFrom) return "not-effective";
  if (c.effectiveUntil && day > c.effectiveUntil) return "expired";
  return now.getTime() - Date.parse(c.reviewedAt) > c.reviewDays * 86400000 ? "review-due" : "reviewed";
}
export function formatMoney(value: number, currency: Currency) { return new Intl.NumberFormat("en-US", { style: "currency", currency, currencyDisplay: "code", minimumFractionDigits: 0, maximumFractionDigits: currency === "JPY" ? 0 : 2 }).format(value); }
export function formatReference(c: CostReference) { return `${formatMoney(c.low, c.currency)}${c.high !== c.low ? `–${formatMoney(c.high, c.currency)}` : ""} / ${c.periodMonths === 1 ? "month" : `${c.periodMonths} months`}`; }
