import type { Metadata } from "next";
import Link from "next/link";
import { GraphStatus } from "@/components/intelligence/Evidence";
import EvidenceLesson from "@/components/intelligence/EvidenceLesson";
import { getIntelligence, identities, identitySource } from "@/lib/intelligence/server";
import { INDICATOR_IDS, INDICATORS, METHODOLOGY_VERSION, evidenceStatus } from "@/lib/intelligence/core";
import { GOVERNMENT_PORTALS } from "@/lib/intelligence/sources";

export const dynamic = "force-dynamic";
export const maxDuration = 60;
export const metadata: Metadata = { title: "Intelligence Graph — Sources & Methodology | TGPI", description: "Inspect TGPI's country evidence, data coverage, confidence rules, update process and limitations.", alternates: { canonical: "https://www.theglobalpolymath.com/intelligence" } };
export default async function IntelligencePage() {
  const state = await getIntelligence();
  const coverage = new Set(state.snapshot.observations.map(o => o.country)).size;
  return <main className="ig-shell"><div className="ig-container">
    <header className="ig-hero"><p className="ig-eyebrow">TGPI Intelligence Graph / Methodology {METHODOLOGY_VERSION}</p><h1>Trust should be inspectable.</h1><p>Country identities, published observations, their sources and the decisions they inform. Connected through explicit identifiers — with uncertainty visible at every step.</p><div className="ig-actions"><Link href="/countries" className="ig-button">Explore the evidence →</Link><Link href="/country-fit" className="ig-button ig-secondary">Build a personal plan</Link></div></header>
    <GraphStatus state={state} />
    <section className="ig-section ig-evidence-grid"><article className="ig-panel"><p className="ig-eyebrow">Identity coverage</p><p className="ig-value">{identities.length} / 195</p><p className="ig-small">TGPI catalog entries mapped to UNSD M49 and ISO identifiers. Names in the interface can be familiar display aliases.</p><a className="ig-link" href={identitySource.url} target="_blank" rel="noreferrer">UNSD identity source ↗</a></article><article className="ig-panel"><p className="ig-eyebrow">Statistical coverage</p><p className="ig-value">{coverage} / 195</p><p className="ig-small">Countries with at least one collected observation. {state.snapshot.observations.length} observations in this revision. Coverage is not a measure of data quality or a claim that every topic is verified.</p></article></section>
    <section className="ig-section ig-panel"><h2>One source of evidence. Several useful decisions.</h2><div className="ig-task-grid">{[["Country dossier", "Inspect the country identity, national context, source, collection date and reference year."], ["Compare", "Compare the same indicators with their units and years visible. Missing values remain missing; different years are disclosed."], ["Country Fit", "Bring your goals and constraints to the evidence. No composite fit percentage or visa prediction is published without a defensible validated model."], ["Personal plan & learning", "Use the gaps to create research tasks, collect your own cost estimates, check official requirements and practice critical interpretation."]].map(([title, detail]) => <article className="ig-task" key={title}><h3>{title}</h3><p className="ig-small">{detail}</p></article>)}</div></section>
    <section className="ig-section"><h2>The data we publish — and what they mean.</h2><div className="ig-evidence-grid">{INDICATOR_IDS.map(id => { const rows = state.snapshot.observations.filter(o => o.indicator === id); return <article key={id} className="ig-panel"><p className="ig-eyebrow">World Development Indicators</p><h3>{INDICATORS[id].label}</h3><p className="ig-small">{INDICATORS[id].explanation}</p><p className="ig-meta">{id} · {INDICATORS[id].unit}<br />{rows.length}/195 available · {rows.filter(o => evidenceStatus(o) === "current").length} within freshness rules<br />Reference-year threshold: {INDICATORS[id].maxAge} years.</p><a href={`https://data.worldbank.org/indicator/${id}`} className="ig-link" target="_blank" rel="noreferrer">Indicator, upstream sources & definitions ↗</a></article>; })}</div></section>
    <section className="ig-section ig-panel"><h2>Confidence without false precision.</h2><p className="ig-small">Our labels describe evidence handling, not the probability a statement is true. “Source checked” requires a registered source, matching indicator and country identifiers, a valid numeric value, complete pagination and an acceptable reference-year age. It does not mean independent factual verification of the producer&apos;s methodology.</p><div className="ig-task-grid">{[["Source checked", "The collection is no more than seven days old and the reference year is within the indicator-specific threshold."], ["Older observation", "The value is traceable but older than the indicator's threshold. It is historical context, not a current-condition claim."], ["Refresh overdue", "Collection is older than seven days. Original dates remain visible and the user is directed to the primary source."], ["Not available", "The source has no usable observation or collection failed. We do not use zero, a regional average or a fabricated estimate."]].map(([title, detail]) => <article className="ig-task" key={title}><h3>{title}</h3><p className="ig-small">{detail}</p></article>)}</div></section>
    <section className="ig-section ig-panel"><h2>Automatic collection. Controlled publication.</h2><p className="ig-small">The application revalidates its shared statistical cache after one hour when requested. A daily scheduled check is configured to request the published API and archive its public snapshot for 90 days. Scheduling can be delayed; this is not a real-time feed. The visible collection date, not the schedule, is the evidence of a successful refresh.</p><p className="ig-small">Only four registered, read-only World Bank API queries are allowed. They contain no user profile information. All four series must pass schema, range, country, year, pagination and minimum-coverage checks before replacing the cached snapshot. Failures retain the last valid cached or bundled observations when available. Cold-start failures without a valid snapshot show missing data.</p><p className="ig-small">Each snapshot has a content revision, methodology version and per-series response digest. Raw response digests make changes detectable; they are not a guarantee that the source is correct. Statistical revisions can change historical values.</p><div className="ig-actions"><a className="ig-link" href="/api/intelligence" target="_blank" rel="noreferrer">Inspect the public graph JSON ↗</a><a className="ig-link" href="https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-about-the-indicators-api-documentation" target="_blank" rel="noreferrer">World Bank API documentation ↗</a></div></section>
    <section className="ig-section ig-panel"><h2>What remains outside automatic verification.</h2><p className="ig-small">Country-specific visa and residence rules, professional licensing, admissions, city living costs, personal safety and taxes need separate sources and contextual review. There are currently {Object.keys(GOVERNMENT_PORTALS).length} reviewed destination-government portal entries, not 195 legal dossiers. A linked government portal does not certify any eligibility claim. Legacy model-generated country budgets and ratings are not used in the new research core.</p><p className="ig-small">The same source-first standard must be applied as we expand to institutions, programs, cities, documents and multilingual content. Education from TGPI is independent: no affiliation, accreditation or endorsement by Harvard, the UN, the World Bank or another university is implied.</p><p className="ig-small">Attribution: World Bank, World Development Indicators, with upstream sources named in each indicator&apos;s metadata; United Nations Statistics Division, M49. Values are displayed with rounding; no missing values are imputed. Dataset-specific reuse terms and third-party rights apply.</p><a className="ig-link" href="https://datacatalog.worldbank.org/public-licenses" target="_blank" rel="noreferrer">World Bank data licensing guidance ↗</a><p className="ig-small">Found an issue? Send the country, indicator, source URL and reference year — no personal documents — to <a className="ig-link" href="mailto:contact@theglobalpolymath.com">contact@theglobalpolymath.com</a>.</p></section>
    <EvidenceLesson /><div className="ig-actions"><Link href="/courses" className="ig-button">Continue learning →</Link><Link href="/country-fit" className="ig-button ig-secondary">Apply this to my plan</Link></div>
  </div></main>;
}
