"use client";
import { useRef, useState } from "react";
import { useUser } from "@clerk/nextjs";
import Link from "next/link";
import { COUNTRY_CURRENCIES, dossierFor, formatMoney, formatReference, referenceReviewState, sourceFor } from "@/lib/intelligence/dossiers";
import SourceReviewNotice from "./SourceReviewNotice";
import { COST_CATEGORIES, PLAN_CURRENCIES, RESEARCH_TASKS, emptyWorksheet, validateWorksheet, worksheetTotals, type ResearchWorksheet, type PlanningCurrency } from "@/lib/intelligence/research-plan";

export default function ResearchWorkbench({ country, countryName }: { country: string; countryName: string }) {
  const { user, isSignedIn, isLoaded } = useUser();
  return <Worksheet key={`${user?.id ?? "guest"}:${country}`} country={country} countryName={countryName} canSave={Boolean(isLoaded && isSignedIn)} />;
}
function Worksheet({ country, countryName, canSave }: { country: string; countryName: string; canSave: boolean }) {
  const [plan, setPlan] = useState<ResearchWorksheet>(() => emptyWorksheet(country, COUNTRY_CURRENCIES[country] ?? "USD"));
  const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const [dirty, setDirty] = useState(false);
  const revision = useRef(0);
  const totals = worksheetTotals(plan); const dossier = dossierFor(country);
  const valid = Boolean(validateWorksheet(plan, [country], RESEARCH_TASKS.map(t => t.id)));
  function update<K extends keyof ResearchWorksheet>(key: K, value: ResearchWorksheet[K]) { revision.current++; setPlan(p => ({ ...p, [key]: value })); setDirty(true); setNotice(""); }
  function numeric(value: string) { return value === "" ? null : Number(value); }
  function changeCurrency(currency: PlanningCurrency) {
    // Currency changes start empty; numbers are never relabelled as a different currency.
    revision.current++; setPlan(p => ({ ...emptyWorksheet(country, currency), city: p.city, months: p.months, completed: p.completed })); setDirty(true); setNotice("Currency changed. Amounts and quote references were cleared; no exchange conversion was performed.");
  }
  async function save() {
    if (!validateWorksheet(plan, [country], RESEARCH_TASKS.map(t => t.id))) { setNotice("Check the amounts, dates and month count before saving."); return; }
    setBusy(true);
    const savingRevision = revision.current;
    try { const response = await fetch("/api/intelligence/worksheet", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(plan) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to save."); if (revision.current === savingRevision) setDirty(false); setNotice(revision.current === savingRevision ? "Saved as your one active private worksheet. Your profile, shortlist and course progress are unchanged." : "The submitted version was saved. Your newer edits are still unsaved."); }
    catch (e) { setNotice(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); }
  }
  async function loadSaved() {
    setBusy(true);
    const loadingRevision = revision.current;
    try { const response = await fetch("/api/intelligence/worksheet", { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to load."); const saved = validateWorksheet(body.worksheet, [country], RESEARCH_TASKS.map(t => t.id)); if (!saved) { setNotice("No saved worksheet for this destination. Only one active worksheet is stored per account."); return; } if (revision.current !== loadingRevision) { setNotice("Loading was not applied because you made new edits. Your inputs were preserved."); return; } setPlan(saved); setDirty(false); setNotice("Your saved worksheet is loaded. Amounts remain your assumptions, not TGPI-verified prices."); }
    catch (e) { setNotice(e instanceof Error ? e.message : "Unable to load."); } finally { setBusy(false); }
  }
  function exportWorksheet() {
    const data = validateWorksheet(plan, [country], RESEARCH_TASKS.map(t => t.id)); if (!data) { setNotice("Check the worksheet fields before exporting."); return; }
    const output = { ...data, exportedAt: new Date().toISOString(), methodology: "User-authored scenario, not an eligibility decision or certified cost estimate", sources: dossier.sources.map(s => ({ id: s.id, url: s.url, reviewedAt: s.reviewedAt })), totals: worksheetTotals(data) };
    const url = URL.createObjectURL(new Blob([JSON.stringify(output, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = `tgpi-${country}-research.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <section id="research-workbench" className="ig-section ig-panel ig-wide" aria-label="Personal decision worksheet">
    <div className="ig-spread"><div><p className="ig-eyebrow">Decision Lab / {countryName}</p><h2>Turn evidence into a workable scenario.</h2><SourceReviewNotice country={country} /></div><span className="ig-badge">Your assumptions · {plan.currency}</span></div>
    <p className="ig-small">Build one scenario in one currency. Blank amounts stay unknown; enter zero only when a cost genuinely does not apply. Changing the country starts a new worksheet. Save or export first. Do not enter identity documents, account numbers or other sensitive identifiers.</p>
    <div className="ig-form-grid"><label>Destination city<input value={plan.city} maxLength={80} placeholder="Your actual city, not a national average" onChange={e => update("city", e.target.value)} /></label><label>Planning currency<select value={plan.currency} onChange={e => changeCurrency(e.target.value as PlanningCurrency)}>{PLAN_CURRENCIES.map(c => <option key={c}>{c}</option>)}</select><span className="ig-meta">Changing currency clears amounts. No automatic FX.</span></label><label>Months in this scenario<input type="number" min={1} max={60} step={1} value={plan.months} onChange={e => update("months", Number(e.target.value))} /></label><label>Contingency, %<input type="number" min={0} max={50} step={1} value={plan.bufferPercent} onChange={e => update("bufferPercent", Number(e.target.value))} /></label></div>
    <div className="ig-form-grid">{COST_CATEGORIES.map(key => <label key={key}>{key[0].toUpperCase() + key.slice(1)}, per month ({plan.currency})<input type="number" inputMode="decimal" min={0} max={100000000} step="any" value={plan.monthly[key] ?? ""} placeholder="Unknown" onChange={e => update("monthly", { ...plan.monthly, [key]: numeric(e.target.value) })} /></label>)}<label>Tuition, entire selected period ({plan.currency})<input type="number" inputMode="decimal" min={0} max={100000000} step="any" value={plan.tuition ?? ""} placeholder="Unknown; 0 only if not applicable" onChange={e => update("tuition", numeric(e.target.value))} /></label><label>Arrival and one-time costs ({plan.currency})<input type="number" inputMode="decimal" min={0} max={100000000} step="any" value={plan.arrival ?? ""} placeholder="Visa, travel, deposits, setup…" onChange={e => update("arrival", numeric(e.target.value))} /></label><label>Quote reference date<input type="date" value={plan.quoteDate} max={new Date().toISOString().slice(0, 10)} onChange={e => update("quoteDate", e.target.value)} /></label><label className="ig-wide">Quote references / short note<input value={plan.sourceNote} maxLength={240} placeholder="e.g. Housing quote and university fee letter, checked on the date above" onChange={e => update("sourceNote", e.target.value)} /></label></div>
    <div className="ig-budget-result" aria-live="polite"><p className="ig-eyebrow">{totals.complete ? "Scenario arithmetic / Not affordability approval" : "Partial subtotal / Not a complete budget"}</p><p className="ig-value">{valid ? totals.missing.length === 7 ? "Not calculated yet" : formatMoney(totals.total, plan.currency) : "Check your inputs"}</p><p className="ig-small">Known monthly amounts × {plan.months} months + tuition for the period + arrival costs + {plan.bufferPercent}% contingency.</p>{valid ? <p className="ig-meta">Known monthly amount: {formatMoney(totals.knownMonthly, plan.currency)} · Contingency: {formatMoney(totals.buffer, plan.currency)}</p> : <p className="ig-caution">Amounts must be non-negative, months 1–60, contingency 0–50%, and quote dates cannot be in the future. Use whole yen for JPY and at most two decimals for other currencies.</p>}{!totals.complete ? <p className="ig-caution">Still unknown: {totals.missing.join(", ")}. The subtotal must not be treated as the money you need.</p> : null}{!plan.quoteDate || !plan.sourceNote ? <p className="ig-caution">Your quote date or source note is missing. The arithmetic does not validate your inputs.</p> : null}</div>
    {dossier.costs.length ? <details className="ig-details"><summary>Consult published references without mixing scopes</summary>{dossier.costs.map(ref => <div key={ref.id}><h3>{ref.title}</h3><p className="ig-small">{formatReference(ref)} · {ref.referencePeriod}<br />{referenceReviewState(ref) !== "reviewed" ? "Review overdue or reference period ended — reconfirm before use." : "Source-reviewed reference; confirm it applies to your case."}<br />{ref.location} · {ref.audience}<br />{ref.category === "total-study" ? "Includes tuition: not comparable with living-only figures." : "Living-only reference: add tuition and other exclusions separately."}</p><a className="ig-link" href={sourceFor(ref.sourceId)!.url} target="_blank" rel="noreferrer">Original source and exclusions ↗</a></div>)}</details> : null}
    <div className="ig-section"><p className="ig-eyebrow">Research checkpoints / {plan.completed.length} of {RESEARCH_TASKS.length} recorded</p><h3>Resolve the decisions that could change your plan.</h3><p className="ig-small">Completion records your own review. It does not certify documents, legal compliance, admission or readiness to travel.</p><div className="ig-task-grid">{RESEARCH_TASKS.map(task => { const related = dossier.claims.filter(c => c.layer === task.layer); return <article className="ig-task" key={task.id}><label className="ig-check-label"><input type="checkbox" checked={plan.completed.includes(task.id)} onChange={e => update("completed", e.target.checked ? [...plan.completed, task.id] : plan.completed.filter(id => id !== task.id))} />{task.title}</label><p className="ig-small">{task.detail}</p>{related.length ? related.slice(0, 2).map(c => <a key={c.id} className="ig-link ig-source-action" href={sourceFor(c.sourceId)!.url} target="_blank" rel="noreferrer">{c.title} ↗</a>) : <p className="ig-meta">A destination-specific source for this step is still missing in this release. Verify directly with the competent authority.</p>}</article>; })}</div></div>
    <div className="ig-actions">{canSave ? <><button className="ig-button" onClick={save} disabled={busy}>{busy ? "Please wait…" : "Save active worksheet"}</button><button className="ig-button ig-secondary" onClick={loadSaved} disabled={busy || dirty}>Load saved worksheet</button></> : <Link className="ig-button" href={`/sign-in?redirect_url=${encodeURIComponent(`/country-fit?country=${country}#research-workbench`)}`}>Sign in to save this worksheet</Link>}<button className="ig-button ig-secondary" type="button" onClick={exportWorksheet}>Export my worksheet</button></div><p className="ig-small" role="status">{notice}</p><p className="ig-meta">{dirty ? "Unsaved edits. Loading is disabled to protect them; save or export before navigating." : "Explicit save only. One active worksheet per account; saving replaces the previous worksheet, not your profile or course progress."}</p>
  </section>;
}
