import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { DOSSIER_CLAIMS, DOSSIER_COUNTRIES, DOSSIER_SOURCES, COST_REFERENCES, dossierFor, reviewState } from "../src/lib/intelligence/dossiers.ts";
import { normalizeSourceText, inspectSourceText } from "../src/lib/intelligence/source-checks.ts";
import { COST_CATEGORIES, RESEARCH_TASKS, emptyWorksheet, validateWorksheet, worksheetTotals } from "../src/lib/intelligence/research-plan.ts";
const NOW = new Date("2026-09-03T12:00:00Z");
const slugs = JSON.parse(readFileSync(new URL("../src/data/intelligence/identities.json", import.meta.url), "utf8")).countries.map(c => c.slug);
const tasks = RESEARCH_TASKS.map(t => t.id);
test("dossier sources and claims have unique identities and known country links", () => {
  for (const rows of [DOSSIER_SOURCES, DOSSIER_CLAIMS, COST_REFERENCES]) { assert.equal(new Set(rows.map(r => r.id)).size, rows.length); for (const row of rows) assert.ok(slugs.includes(row.country)); }
  assert.equal(DOSSIER_COUNTRIES.length, 8);
  for (const claim of DOSSIER_CLAIMS) { const source = DOSSIER_SOURCES.find(s => s.id === claim.sourceId); assert.equal(source.country, claim.country); assert.ok(source.reviewedAt); assert.notEqual(source.status, "unconfirmed"); for (const key of ["audience", "limits", "referencePeriod", "reviewedAt"]) assert.ok(claim[key]); assert.ok(claim.questions.length >= 2); }
});
test("registered sources use fixed public HTTPS URLs with no credentials or fragments", () => { for (const source of DOSSIER_SOURCES) { const url = new URL(source.url); assert.equal(url.protocol, "https:"); assert.equal(url.username, ""); assert.equal(url.password, ""); assert.equal(url.hash, ""); if (source.automaticCheck) assert.ok(source.markers.length); if (!source.reviewedAt) assert.equal(source.automaticCheck, false); } });
test("a country outside the editorial wave has explicit missing layers", () => { const dossier = dossierFor("vatican-city"); assert.deepEqual(dossier, { claims: [], sources: [], costs: [] }); assert.deepEqual(dossierFor("__proto__"), dossier); });
test("review dates cannot be renewed by availability checks", () => { const c = DOSSIER_CLAIMS.find(c => c.id === "ca-funding-2026"); assert.equal(reviewState(c, NOW), "reviewed"); assert.equal(reviewState(c, new Date("2026-10-04")), "review-due"); assert.equal(reviewState(c, new Date("2026-08-31")), "not-effective"); const de = DOSSIER_CLAIMS.find(c => c.id === "de-study-route"); assert.equal(reviewState(de, new Date("2027-01-01")), "expired"); });
test("Canada’s dated funds threshold is not promoted to a living-cost estimate", () => { const c = DOSSIER_CLAIMS.find(c => c.id === "ca-funding-2026"); assert.equal(c.kind, "requirement"); assert.equal(c.effectiveFrom, "2026-09-01"); assert.match(c.summary, /23,448/); assert.match(c.limits, /Quebec/); assert.equal(dossierFor("canada").costs.length, 0); });
test("cost references retain distinct currencies, periods, categories and source years", () => { const ox = COST_REFERENCES.find(c => c.id === "oxford-2026"); const mit = COST_REFERENCES.find(c => c.id === "mit-2026"); const jp = COST_REFERENCES.find(c => c.id === "japan-jasso-2023"); assert.deepEqual([ox.low, ox.high, ox.currency, ox.periodMonths, ox.category], [1405, 2105, "GBP", 1, "living"]); assert.deepEqual([mit.low, mit.currency, mit.periodMonths, mit.category], [109017, "USD", 9, "total-study"]); assert.equal(jp.historical, true); assert.match(jp.referencePeriod, /2023/); });
test("source normalization ignores scripts and preserves inspectable text", () => { assert.equal(normalizeSourceText('<main>2026–27&nbsp;<b>£1,405</b><script>ignore()</script></main>'), '2026-27 £1,405'); });
test("source marker success is not labelled legal or factual verification", () => { const s = DOSSIER_SOURCES.find(s => s.id === "uk-oxford"); const r = inspectSourceText(s, `<main>${"Context ".repeat(20)}2026-27 £1,405 £2,105</main>`); assert.equal(r.status, "markers-present"); assert.equal(r.matchedMarkers, 3); assert.match(r.message, /not a legal or factual/); });
test("missing markers, empty pages and access challenges require review", () => { const s = DOSSIER_SOURCES[0]; for (const body of ["", "<html><h1>Just a moment</h1></html>", `<main>${"Unexpected content ".repeat(30)}</main>`]) assert.equal(inspectSourceText(s, body).status, "review-needed"); });
test("null costs remain unknown and are not marked as a complete budget", () => { const p = emptyWorksheet("portugal", "EUR"); assert.ok(validateWorksheet(p, slugs, tasks, NOW)); assert.equal(worksheetTotals(p).missing.length, 7); assert.equal(worksheetTotals(p).complete, false); });
test("explicit zero is allowed without inventing missing values", () => { const p = emptyWorksheet("portugal", "EUR"); p.monthly.housing = 0; assert.equal(worksheetTotals(p).missing.length, 6); assert.equal(p.monthly.food, null); });
test("worksheet arithmetic includes period costs once and computes the declared contingency", () => { const p = emptyWorksheet("portugal", "EUR"); p.monthly = { housing: 1000, food: 300, transport: 100, health: 100, other: 100 }; p.tuition = 6000; p.arrival = 2000; const t = worksheetTotals(p); assert.equal(t.knownMonthly, 1600); assert.equal(t.base, 27200); assert.equal(t.total, 29920); assert.equal(t.complete, true); });
test("worksheet schema rejects hostile or impossible values", () => { const p = emptyWorksheet("portugal", "EUR"); for (const patch of [{ country: "unknown" }, { currency: "BTC" }, { months: 0 }, { months: 1.5 }, { months: 61 }, { bufferPercent: -1 }, { bufferPercent: Infinity }, { tuition: -1 }, { arrival: "2000" }, { quoteDate: "2026-02-31" }, { quoteDate: "2027-01-01" }, { quoteDate: "tomorrow" }, { completed: ["legally-approved"] }, { city: "x".repeat(81) }, { sourceNote: "x".repeat(241) }, { monthly: { ...p.monthly, housing: NaN } }]) assert.equal(validateWorksheet({ ...p, ...patch }, slugs, tasks, NOW), null, JSON.stringify(patch)); });
test("worksheet normalization strips caller-provided identity and authority claims", () => { const p = validateWorksheet({ ...emptyWorksheet("japan", "JPY"), userId: "someone-else", approved: true, completed: ["route", "route"] }, slugs, tasks, NOW); assert.equal(p.userId, undefined); assert.equal(p.approved, undefined); assert.deepEqual(p.completed, ["route"]); });
test("all cost category inputs are represented once", () => { assert.equal(new Set(COST_CATEGORIES).size, 5); const p = emptyWorksheet("canada", "CAD"); assert.deepEqual(Object.keys(p.monthly), [...COST_CATEGORIES]); });
test("new source retrieval is bounded and never accepts a caller URL", () => { const source = readFileSync(new URL("../src/lib/intelligence/source-watch.server.ts", import.meta.url), "utf8"); assert.match(source, /fetch\(source.url/); assert.match(source, /redirect: "manual"/); assert.match(source, /AbortSignal.timeout\(8000\)/); assert.match(source, /1_500_000/); assert.match(source, /\[401, 403\]/); assert.match(source, /revalidate: 21600/); });
test("currency changes clear values and asynchronous reads preserve newer edits", () => { const source = readFileSync(new URL("../src/components/intelligence/ResearchWorkbench.tsx", import.meta.url), "utf8"); assert.match(source, /emptyWorksheet\(country, currency\)/); assert.match(source, /revision.current !== loadingRevision/); assert.match(source, /revision.current === savingRevision/); assert.match(source, /user\?\.id \?\? "guest"/); assert.doesNotMatch(source, /localStorage|sessionStorage/); });
