import type { Metadata } from "next";
import Link from "next/link";
import { DOSSIER_CLAIMS, DOSSIER_COUNTRIES, DOSSIER_REVIEW_DATE, DOSSIER_SOURCES, dossierFor } from "@/lib/intelligence/dossiers";
import { getCountry } from "@/lib/countries";
import SourceRegister from "@/components/intelligence/SourceRegister";

export const metadata: Metadata = { title: "Decision Dossiers — Study, Costs & Official Sources | TGPI", description: "Research study pathways, institution recognition, scoped cost references and personal planning with explicit source coverage.", alternates: { canonical: "https://www.theglobalpolymath.com/intelligence/research" } };
export default function ResearchPage() {
  return <main className="ig-shell"><div className="ig-container"><header className="ig-hero"><p className="ig-eyebrow">TGPI Intelligence / Decision dossiers</p><h1>The next decision<br />needs a deeper answer.</h1><p>Move beyond country averages. Inspect study pathways, institution checks and cost assumptions — then build a personal scenario that keeps the unknowns visible.</p><div className="ig-actions"><Link href="/country-fit#research-workbench" className="ig-button">Open my Decision Lab →</Link><Link href="/intelligence" className="ig-link">Read the methodology</Link></div></header>
    <section className="ig-section ig-panel"><p className="ig-eyebrow">Release scope / {DOSSIER_REVIEW_DATE}</p><h2>Coverage is visible, not implied.</h2><p className="ig-small">{DOSSIER_COUNTRIES.length} initial destinations · {DOSSIER_CLAIMS.length} source-linked summaries · {DOSSIER_SOURCES.filter(s => s.reviewedAt).length} sources with a completed content review. Coverage differs by layer. These are study-focused research dossiers, not complete legal files or a ranking of countries. {DOSSIER_SOURCES.filter(s => !s.reviewedAt).length} additional source pointers remain unconfirmed and are clearly marked.</p><p className="ig-small">The same worksheet works for all 195 country identities. A missing local estimate stays missing; a visa financial threshold is never labelled as a city’s living cost.</p></section>
    <section className="ig-section ig-country-grid" aria-label="Research destinations">{DOSSIER_COUNTRIES.map(slug => { const country = getCountry(slug)!; const dossier = dossierFor(slug); return <article className="ig-panel" key={slug}><p className="ig-eyebrow">{country.emoji} {country.name}</p><h2>{country.name}</h2><div className="ig-coverage-list">{(["entry", "education", "cost"] as const).map(layer => { const count = dossier.claims.filter(c => c.layer === layer).length; return <p key={layer}><span>{layer === "entry" ? "Entry / residence" : layer === "education" ? "Education" : "Cost / funding"}</span><span className={`ig-badge ${count ? "" : "ig-historical"}`}>{count ? `${count} ${count === 1 ? "summary" : "summaries"}` : "Not yet covered"}</span></p>; })}</div><div className="ig-actions"><Link className="ig-button" href={`/countries/${slug}#research-dossier`}>Inspect dossier →</Link><Link className="ig-link" href={`/country-fit?country=${slug}#research-workbench`}>Build a scenario</Link></div></article>; })}</section>
    <SourceRegister />
    <section className="ig-section ig-panel"><h2>Four questions before trusting any number.</h2><ol className="ig-question-list"><li>Is this a requirement, an estimate, a historical observation or my own assumption?</li><li>Does the source describe my city, programme, household and application date?</li><li>Are the currency, period and exclusions the same as the comparison?</li><li>What must the responsible authority or institution confirm before I commit?</li></ol><p className="ig-small">Institutional sources are cited for their published information. TGPI has no implied affiliation, accreditation or endorsement from the universities, agencies or governments referenced.</p></section>
  </div></main>;
}
